export const HonestyQuestions = [
    'If a wallet with identification, credit cards, and $200 in cash is purposely left on the sidewalk by a newspaper reporter to see whether it will be returned as found with the cash and credit cards, most people would be honest enough to immediately return the wallet to its owner.',
    'Very few people ever have taken anything that didn’t belong to them because they understand there are boundaries of ownership that are not to be crossed for any reason.',
    'You can trust the majority of people.',
    'Most shoplifters are children.',
    'Children who take money or jewelry from a friend’s house should be made to apologize, return the item, earn money doing chores or community service, and buy that friend a similar gift.',
    'No one I knew as a child or adolescent shoplifted.',
    'It’s very important that parents and teachers reward children for being honest.',
    'Most parents think that it’s normal for children to steal small toys that the parents cannot afford.',
    'If someone says he or she has never stolen or shoplifted, I naturally believe the person.',
    'Shoplifting laws are too lenient.',
    'Shoplifters should be punished with long-term jail time.',
    'It’s okay to buy stolen merchandise if you can get it cheap at a thrift store.',
    'Everyone I know is honest.',
    'If you’re undercharged, it’s okay to not bring it to the attention of the management.',
    'If you take office supplies home, it’s okay because you’re probably underpaid.',
    'Everybody steals pencils and pens from the boss.',
    'It’s acceptable to steal time by leaving the office early when there’s no work to do.',
    'It’s proper to call in sick when you’re healthy and just want to go to a movie or the beach.',
    'Everybody steals something at work—time, days off, or office supplies.',
    'I strongly agree that finders are keepers of anything found in public places.',
    'If my boss sends me a paycheck with more money than I earned, I’ll keep it without bringing the error to my boss’s attention.',
    'It’s okay to take a week off from work for my honeymoon by calling in sick.',
    'If I see my supervisor stealing, I’ll tell my co-workers, but not inform the company headquarters in another city.',
    'If a co-worker uses illegal drugs on the job, it’s right to report it to the boss, even though I’ll probably be sabotaged by my co-workers for snitching.',
    'Employees who take home dog food without permission from discount stores are not really stealing if they donate the pet food to feed dogs owned by elderly shut-ins who are delivered hot meals.'
]